Repository ootd-zip/server, pull requests merged in 2024-03, with the labels that each got.

#125 Feature/get ootds(#124)
  src/main/java/zip/ootd/ootdzip/ootd/controller/OotdController.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetByUserReq.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetByUserRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdPatchReq.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdPutReq.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepository.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/ootdimage/repository/OotdImageRepository.java
  src/test/java/zip/ootd/ootdzip/ootd/controller/OotdControllerTest.java
  src/test/java/zip/ootd/ootdzip/ootd/service/OotdServiceTest.java
Labels: enhancement

#126 Feature/search clothes
  src/main/java/zip/ootd/ootdzip/category/data/DetailCategory.java
  src/main/java/zip/ootd/ootdzip/category/domain/Category.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/ClothesController.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/SaveClothesReq.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/UpdateClothesIsOpenReq.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/UpdateClothesIsPrivateReq.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/UpdateClothesReq.java
  src/main/java/zip/ootd/ootdzip/clothes/data/ClothesColorDto.java
  src/main/java/zip/ootd/ootdzip/clothes/data/FindClothesRes.java
  src/main/java/zip/ootd/ootdzip/clothes/domain/Clothes.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepository.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesService.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/SaveClothesSvcReq.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/UpdateClothesIsPrivateSvcReq.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/UpdateClothesSvcReq.java
  src/main/java/zip/ootd/ootdzip/common/exception/GlobalExceptionHandler.java
  src/test/java/zip/ootd/ootdzip/clothes/controller/ClothesControllerTest.java
  src/test/java/zip/ootd/ootdzip/clothes/domain/ClothesTest.java
  src/test/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryTest.java
  src/test/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImplTest.java
Labels: enhancement

#127 Feature/mypage
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
  src/main/java/zip/ootd/ootdzip/common/entity/BaseEntity.java
  src/main/java/zip/ootd/ootdzip/common/exception/code/ErrorCode.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetAllRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetRes.java
  src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
  src/main/java/zip/ootd/ootdzip/user/controller/request/ProfileReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/request/UserRegisterReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/response/ProfileRes.java
  src/main/java/zip/ootd/ootdzip/user/controller/response/UserInfoForMyPageRes.java
  src/main/java/zip/ootd/ootdzip/user/data/ProfileRes.java
  src/main/java/zip/ootd/ootdzip/user/data/UserRegisterReq.java
  src/main/java/zip/ootd/ootdzip/user/domain/User.java
  src/main/java/zip/ootd/ootdzip/user/domain/UserStyle.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/main/java/zip/ootd/ootdzip/user/service/request/ProfileSvcReq.java
  src/main/java/zip/ootd/ootdzip/user/service/request/UserInfoForMyPageSvcReq.java
  src/main/java/zip/ootd/ootdzip/user/service/request/UserRegisterSvcReq.java
  src/test/java/zip/ootd/ootdzip/ControllerTestSupport.java
  src/test/java/zip/ootd/ootdzip/clothes/controller/ClothesControllerTest.java
  src/test/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImplTest.java
  src/test/java/zip/ootd/ootdzip/user/controller/UserControllerTest.java
  src/test/java/zip/ootd/ootdzip/user/service/UserServiceTest.java
Labels: enhancement

#129 마이페이지 OOTD 조회수정 및 래퍼타입변경
  src/main/java/zip/ootd/ootdzip/comment/data/CommentGetAllRes.java
  src/main/java/zip/ootd/ootdzip/comment/domain/Comment.java
  src/main/java/zip/ootd/ootdzip/common/response/CommonSliceResponse.java
  src/main/java/zip/ootd/ootdzip/ootd/controller/OotdController.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetAllRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetByUserRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetOtherRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetRes.java
  src/main/java/zip/ootd/ootdzip/ootd/domain/Ootd.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepository.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/test/java/zip/ootd/ootdzip/ootd/controller/OotdControllerTest.java
  src/test/java/zip/ootd/ootdzip/ootd/service/OotdServiceTest.java
Labels: bug, enhancement

#132 feature : 옷 조회시 userId 추가
  src/main/java/zip/ootd/ootdzip/clothes/controller/ClothesController.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/response/FindClothesRes.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesService.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
  src/test/java/zip/ootd/ootdzip/clothes/controller/ClothesControllerTest.java
  src/test/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImplTest.java
Labels: enhancement

#136 신고항목 여러개 선택할 수 있도록 변경
  src/main/java/zip/ootd/ootdzip/report/controller/request/ReportReq.java
  src/main/java/zip/ootd/ootdzip/report/service/request/ReportSvcReq.java
  src/main/java/zip/ootd/ootdzip/report/service/strategy/ReportClothesStrategy.java
  src/main/java/zip/ootd/ootdzip/report/service/strategy/ReportCommentStrategy.java
  src/main/java/zip/ootd/ootdzip/report/service/strategy/ReportOotdStrategy.java
  src/main/java/zip/ootd/ootdzip/report/service/strategy/ReportStrategy.java
  src/test/java/zip/ootd/ootdzip/report/controller/ReportControllerTest.java
  src/test/java/zip/ootd/ootdzip/report/service/ReportServiceTest.java
  src/test/java/zip/ootd/ootdzip/report/service/strategy/ReportClothesStrategyTest.java
  src/test/java/zip/ootd/ootdzip/report/service/strategy/ReportCommentStrategyTest.java
  src/test/java/zip/ootd/ootdzip/report/service/strategy/ReportOotdStrategyTest.java
Labels: enhancement

#134 알림기능구현
  src/main/java/zip/ootd/ootdzip/comment/data/CommentGetAllRes.java
  src/main/java/zip/ootd/ootdzip/comment/domain/Comment.java
  src/main/java/zip/ootd/ootdzip/comment/service/CommentService.java
  src/main/java/zip/ootd/ootdzip/common/config/AsyncConfig.java
  src/main/java/zip/ootd/ootdzip/common/util/TimeUtil.java
  src/main/java/zip/ootd/ootdzip/notification/controller/NotificationController.java
  src/main/java/zip/ootd/ootdzip/notification/data/NotificationGetAllReq.java
  src/main/java/zip/ootd/ootdzip/notification/data/NotificationGetAllRes.java
  src/main/java/zip/ootd/ootdzip/notification/data/NotificationRes.java
  src/main/java/zip/ootd/ootdzip/notification/domain/Notification.java
  src/main/java/zip/ootd/ootdzip/notification/domain/NotificationType.java
  src/main/java/zip/ootd/ootdzip/notification/event/NotificationEvent.java
  src/main/java/zip/ootd/ootdzip/notification/event/NotificationEventListener.java
  src/main/java/zip/ootd/ootdzip/notification/repository/EmitterRepository.java
  src/main/java/zip/ootd/ootdzip/notification/repository/NotificationRepository.java
  src/main/java/zip/ootd/ootdzip/notification/service/NotificationService.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/test/java/zip/ootd/ootdzip/ControllerTestSupport.java
  src/test/java/zip/ootd/ootdzip/comment/domain/CommentTest.java
  src/test/java/zip/ootd/ootdzip/common/util/TimeUtilTest.java
  src/test/java/zip/ootd/ootdzip/notification/controller/NotificationControllerTest.java
  src/test/java/zip/ootd/ootdzip/notification/domain/NotificationTest.java
  src/test/java/zip/ootd/ootdzip/notification/repository/NotificationRepositoryTest.java
  src/test/java/zip/ootd/ootdzip/notification/service/NotificationAsyncServiceTest.java
  src/test/java/zip/ootd/ootdzip/notification/service/NotificationServiceTest.java
  src/test/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryTest.java
Labels: enhancement

#140 읽지않은 알림있는지 확인하는 API 추가
  src/main/java/zip/ootd/ootdzip/notification/controller/NotificationController.java
  src/main/java/zip/ootd/ootdzip/notification/repository/NotificationRepository.java
  src/main/java/zip/ootd/ootdzip/notification/service/NotificationService.java
  src/test/java/zip/ootd/ootdzip/notification/repository/NotificationRepositoryTest.java
  src/test/java/zip/ootd/ootdzip/notification/service/NotificationServiceTest.java
Labels: enhancement

#138 댓글, 알람, OOTD, 북마크 수정 삭제시 본인인지 확인하는 로직 추가
  src/main/java/zip/ootd/ootdzip/comment/service/CommentService.java
  src/main/java/zip/ootd/ootdzip/notification/service/NotificationService.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/ootdbookmark/service/OotdBookmarkService.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/test/java/zip/ootd/ootdzip/comment/service/CommentServiceTest.java
  src/test/java/zip/ootd/ootdzip/notification/service/NotificationServiceTest.java
  src/test/java/zip/ootd/ootdzip/ootd/service/OotdServiceTest.java
  src/test/java/zip/ootd/ootdzip/ootdbookmark/service/OotdBookmarkServiceTest.java
Labels: enhancement

#143 이 옷을 활용한 OOTD 기능 추가
  src/main/java/zip/ootd/ootdzip/ootd/controller/OotdController.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetClothesReq.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdGetClothesRes.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/ootdimage/repository/OotdImageRepository.java
  src/test/java/zip/ootd/ootdzip/ootd/controller/OotdControllerTest.java
  src/test/java/zip/ootd/ootdzip/ootd/service/OotdServiceTest.java
  src/test/java/zip/ootd/ootdzip/ootdimage/repository/OotdImageRepositoryTest.java
Labels: enhancement

#145 알람 수정
  src/main/java/zip/ootd/ootdzip/comment/service/CommentService.java
  src/main/java/zip/ootd/ootdzip/notification/data/NotificationGetAllRes.java
  src/main/java/zip/ootd/ootdzip/notification/event/NotificationEvent.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
Labels: enhancement

#148 옷 조회 시 필터 조건 추가
  .gitignore
  build.gradle
  src/main/java/zip/ootd/ootdzip/clothes/controller/ClothesController.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/FindClothesByUserReq.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/SearchClothesReq.java
  src/main/java/zip/ootd/ootdzip/clothes/controller/response/SearchClothesRes.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepository.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryCustom.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesService.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/FindClothesByUserSvcReq.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/SearchClothesSvcReq.java
  src/main/java/zip/ootd/ootdzip/common/config/QuerydslConfiguration.java
  src/test/java/zip/ootd/ootdzip/clothes/controller/ClothesControllerTest.java
  src/test/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImplTest.java
  src/test/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImplTest.java
  src/test/java/zip/ootd/ootdzip/user/UserRepositoryTest.java
Labels: enhancement

#152 알람 DTO 수정
  src/main/java/zip/ootd/ootdzip/notification/data/NotificationGetAllRes.java
Labels: bug

#153 검색 기능 추가
  src/main/java/zip/ootd/ootdzip/clothes/controller/response/SearchClothesRes.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/ootd/controller/OotdController.java
  src/main/java/zip/ootd/ootdzip/ootd/controller/request/OotdSearchReq.java
  src/main/java/zip/ootd/ootdzip/ootd/controller/response/OotdSearchRes.java
  src/main/java/zip/ootd/ootdzip/ootd/data/OotdSearchSortType.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepository.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryCustom.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/ootd/service/request/OotdSearchSvcReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
  src/main/java/zip/ootd/ootdzip/user/controller/request/UserSearchReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/response/UserSearchRes.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserRepository.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserRepositoryCustom.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/main/java/zip/ootd/ootdzip/user/service/request/UserSearchSvcReq.java
  src/test/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryTest.java
  src/test/java/zip/ootd/ootdzip/querydsl/QueryDslExample.java
  src/test/resources/application.yaml
Labels: enhancement

#154 검색 기능 수정
  src/main/java/zip/ootd/ootdzip/clothes/controller/request/SearchClothesReq.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryCustom.java
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
  src/main/java/zip/ootd/ootdzip/clothes/service/request/SearchClothesSvcReq.java
  src/main/java/zip/ootd/ootdzip/ootd/controller/request/OotdSearchReq.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/ootd/service/OotdService.java
  src/main/java/zip/ootd/ootdzip/ootd/service/request/OotdSearchSvcReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/request/UserSearchReq.java
  src/test/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImplTest.java
  src/test/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryTest.java
Labels: enhancement

#156 Feature/user style
  src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
  src/main/java/zip/ootd/ootdzip/user/controller/request/UserStyleUpdateReq.java
  src/main/java/zip/ootd/ootdzip/user/controller/response/UserInfoForMyPageRes.java
  src/main/java/zip/ootd/ootdzip/user/controller/response/UserStyleRes.java
  src/main/java/zip/ootd/ootdzip/user/domain/User.java
  src/main/java/zip/ootd/ootdzip/user/domain/UserStyle.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserStyleRepository.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/main/java/zip/ootd/ootdzip/user/service/request/UserStyleUpdateSvcReq.java
  src/test/java/zip/ootd/ootdzip/user/controller/UserControllerTest.java
  src/test/java/zip/ootd/ootdzip/user/service/UserServiceTest.java
Labels: enhancement

#158 Feature/follower(#155)
  src/main/java/zip/ootd/ootdzip/user/controller/request/UserSearchReq.java
  src/main/java/zip/ootd/ootdzip/user/data/UserSearchType.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserRepositoryCustom.java
  src/main/java/zip/ootd/ootdzip/user/repository/UserRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/user/service/UserService.java
  src/main/java/zip/ootd/ootdzip/user/service/request/UserSearchSvcReq.java
  src/test/java/zip/ootd/ootdzip/user/repository/UserRepositoryImplTest.java
  src/test/java/zip/ootd/ootdzip/user/service/UserServiceTest.java
Labels: enhancement

#160 Fix/search
  src/main/java/zip/ootd/ootdzip/clothes/repository/ClothesRepositoryImpl.java
  src/main/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryImpl.java
  src/test/java/zip/ootd/ootdzip/ootd/repository/OotdRepositoryTest.java
Labels: bug
